### ISSUE TITLE
Devices lost in HomeKit when cube isn't found on startup

### ISSUE THREAD

**Issue by normen** [tobsch/homebridge-platform-maxcube#10]
To keep the plugin from blocking the startup of the HomeBridge server when no Max! Cube is found an empty list of Accessories is reported. This however causes HomeKit to remove all references to the Accessories so that the user has to set up all devices again when the cube is available again.

To avoid this the plugin SHOULD actually block the HomeKit server startup - we can assume that if the user added the Cube to the configuration he will want to use it. The fix should be easy, theres even a comment boasting about how smart it is to not block the server startup :)

**Comment by DanielWeeber** [comment]
Whats the point with reporting an empty list of Accessories? No other plugin does that.

**Comment by normen** [comment]
The first sentence of the issue explains that?

**Comment by DanielWeeber** [comment]
Compare any other plugin that connects to something - it does not need to report a empty list of accessories to prevent the plugin from blocking the startup. 

Therefore I asked.

**Comment by normen** [comment]
Well this whole issue is about changing that behavior? I don't understand what information you want that isn't presented here?

**Comment by DanielWeeber** [comment]
Maybe my point was not clear - sorry. I just wanted to check if the MAX! Cube or the library 
forces us to report an empty list. If not it should be safe to remove.

**Comment by normen** [comment]
So are you asking why I called the callback with an empty array instead of just calling it empty to prevent the blocking? Because the server does block if the callback isn't called, that much is expected and normal.

If that was the question then the answer is that it was the first thing to come to my mind to stop the blocking from happening.

**Comment by normen** [comment]
At any instance, the whole behavior should be changed anyway. It SHOULD block.
