### ISSUE TITLE
Window Sensors

### ISSUE THREAD

**Issue by solbadguy2010** [tobsch/homebridge-platform-maxcube#11]
Hi, this is more a request than an Issue.

currently i connect to my MAX Cube by using FHEM. Then i connect Homebridge to FHEM.
Since your plugin is really working great i would like to get rid of FHEM in the middle.
Sadly FHEM is showing me the On/Off state of the MAX Window sensors and your plugin does not.
Is there any way you could add them to your Plugin?

Thank you!

**Comment by normen** [comment]
You can see if the window is open by looking at the temperature. If its 12 degrees the window is open. Otherwise no, the underlying library we use to access the cube doesn't expose that info.

**Comment by solbadguy2010** [comment]
Hi, yes, i know that. But i have a big living room with multiple windows and sensors on them. It would be great to see which window is open.
But if your library isn`t able to read them i think i stay with FHEM.
Thanks for your help anyway!

**Comment by normen** [comment]
As said, its the underlying library, you could ask them if its possible to implement that:
https://github.com/ivesdebruycker/maxcube

**Comment by solbadguy2010** [comment]
Thank you for the feedback.
I think some other user already wanted this to happen and there is already a commit to merge that into the master release:
https://github.com/ivesdebruycker/maxcube/pull/23

hopefully we see that feature in the future

**Comment by DanielWeeber** [comment]
+1 must have
I just asked if it can be merged

**Comment by DanielWeeber** [comment]
For reference see my fork https://github.com/DanielWeeber/homebridge-platform-maxcube
This will also pull the forked version of the library. I added a new .js file for the Contact Sensors and made a few changes in the index.js.

All window sensors now get added to HomeKit and the automatic refresh is working just fine.
