### ISSUE TITLE
Window Contact & Multiple Actuators in one Room

### ISSUE THREAD

**Issue by MGPhil** [tobsch/homebridge-platform-maxcube#16]
Hi,
just installed your Plugin and it works really great but I have some problems and one feature request, may you can help me? 

The problem is that if I have more then one radiator actuator in one room without a wall thermostat and set the temperature by hand to some value nothing happens, when I set the complete room via Siri to a temperature it works, what do I make wrong?

Also the Cooling button I dont understand, how does your three modes (Heating/Cooling/Auto) compare to only the two (Auto & Manual) from MaxCube/eq-3?

Another point is that if I had opened one window I cannot set a the temperature anymore.
It just stays on the predefined window open temperature, is that a ok behavior?

The Feature request would be to add the Window Contact(s) to Homekit so that it is possible to see the status of the windows and also be able to automate/react to things when opening a window.

Best regards & Thanks again for your really great plugin.

Philipp

**Comment by normen** [comment]
a) As written in the manual, just wait for a while, the temperature will appear in HomeKit
b) This is described in the manual.
c) Yes, that is how the Max! Cube works, as described in the Max! Cube manual.
d) This functionality is being added right now and will be available in the plugin with the next release. For now you can just set your scenes to react to a set temperature of "12", which is what is set when a window opens.

**Comment by MGPhil** [comment]
Hi, thanks for the answer, but may I dont get something:
a)The actual and set temp is in homekit but if I change the set temp with the slider homekit sets the temp but after next cube refresh it is back to the temp were it was before I changed it with the slider. When I change temp with Siri everything works as expected.
b) Yes I read that, "Off, Heating and Auto" is clear but what Cooling is I dont get.
c) Thanks for the Info, may you could then lock the actuator that you also in homekit cannot change the temp when the cube does not allow it and only see the window open set temp and the actual temp?
d) ok really cool that you add that also

**Comment by normen** [comment]
a) Can't say that happens for me.. I have three thermostats in one room and can set the room temperature via any of them.
b) I don't know how to express it better than I did in the manual: "The thermostat is set to manual mode, temperature is kept as is if above 10. The thermostat will report "HEATING" when next polled." So "cooling" does exactly the same thing as "heating".
c) I don't see the point really as the temperature will not be set and HomeKit will fall back to the actual temperature.
