### ISSUE TITLE
Wall thermostat in room without radiator thermostat

### ISSUE THREAD

**Issue by MGPhil** [tobsch/homebridge-platform-maxcube#21]
Hi, I would like to use wall thermostats as temperature sensors in rooms without radiators (or any other max! product). I see the set temperature (and can change it on the wall thermostat) but the actual temperature stays at 0°C for two days now. What do I make wrong?

**Comment by normen** [comment]
Let the homebridge server run for a while, each time you restart it the temperature data is reset to zero.

The Max! thermostats do not always report a temperature and as long as they didn't report a temperature yet the plugin will display "0 degrees" in HomeKit. As soon as they reported a different temperature for the first time that temperature is displayed.

**Comment by MGPhil** [comment]
3 days now still 0°C, when I change the set temp this gets updated in homekit quite fast.
In the max! webpage/software the room looks different because it has no radiator thermostat.

Can you tell me what the standard update time is?

One additional question I updated to 0.9.3 and still have now window contacts in homekit, was my update wrong or are you still working on that topic? Thanks

**Comment by normen** [comment]
The readme states the default update time.

If the temp isn't reported it isn't reported, not much the plugin can do there. Its normal that the set temperature is picked up more quickly, its not a connection issue, the thermostat simply reports "0". There could be an issue in the underlying library reporting 0 falsely or the Max! software simply displays a default temperature but both are out of the scope of this particular plugin.

To enable window contacts set "windowcontact" to true in the config, its still in testing but seems to work fine.

**Comment by MGPhil** [comment]
Just read the readme again and you only tell that you can change the default time and give an example how to change with 10 minutes but you don't state that this is the default if you add nothing. So please just confirm that 10min is default, thanks.

The temp is reportet to the PC GUI and I see correct values there, only in homekit it stays 0°C for 3 days now. If that is out of your plugin scope to get stable actual temp values from wall thermostats then I will have to live with that, sad to hear...

Thanks for the hint how to turn on the windowcontact feature, I appreciate that

**Comment by normen** [comment]
I think I mention the update time in the readme, i.e. how long it takes max until you see a change, otherwise check the code, I can't say off the top of my head, thanks.

Anyway this isn't a support service for a free plugin but a bug tracker. As the bug would be in the library we use and not in this plugin I'll bow out of the discussion now.

**Comment by MGPhil** [comment]
Was in my optinion not a support,  I want you only to tell what problems I have with the plugin because my you or others come and the same problem situation, but as I mentioned I appreciate your time to answer my questions, thanks.

I also tried adding "windowcontact" : "true" to my homebridge config but nothing happend...may that also is more a support topic then issue but were or who should I ask else if I have troubles then the programmer?

**Comment by normen** [comment]
So do you need help or not? If you do need help it IS support, right? :)

See this is for users helping developers, not the other way around. This is free software in alpha/beta state, it has some documentation and you even have all the code. And with a bit of looking around here on github you would have seen in the pull request that its "windowsensor": true, just like I did just now, spending 3 minutes of my private time just for you - do you see what I am getting at? ;)

If you now say "But why didn't you put that in the readme then?" I ask you "Why aren't you already reading the github documentation, making a fork and editing the readme so you can send a PR?" (;

**Comment by MGPhil** [comment]
I looked around on github and in the files but have not found this, anyway thanks for your time again
