### ISSUE TITLE
Return to AUTO mode

### ISSUE THREAD

**Issue by amorgos** [tobsch/homebridge-platform-maxcube#32]
Hi,
When I return from manual to auto mode in HomeKit iOS app my device (radiator, wall term) are set to Auto but .... the temeperature stays the same as set during Manual mode. It changes only during next period change.  How can I make HomeKit to change device to AUTO together with scheduled temperature (this is standard behavior when one changes from manu to auto using device button or official app).

Aleksander

**Comment by normen** [comment]
Create a scene that includes the temperature and auto mode and use that. The behavior in the plugin will not be changed.

**Comment by amorgos** [comment]
Thanks. It doesn’t help much because it doesn’t set pre-configured schedule then. 

Sometimes it happens that someone changes temperature temporary using physical button (or HomeKit) and after some time wants to return to the schedule without setting temperature. Temperature should be taken from pre-configured schedule then and could be different depending on time.

Another scenario. Suppose I’ve been away from home and set everything to ECO (globally) which means all radiators has been set e.g. 17C. Then I’m returning and want to have everything return to AUTO according to the pre-configured schedule for the movement of returning (which might be different for every radiator and every period of time and is stored in MaxCube or even at the level of single radiator). Normally using official MaxCube app I can just click auto for whole home and everything is set to current auto schedule. I have even special ECO button to do it near to my front door but I’d like to make use of HomeKit away automation rules (e.g. HomeKit detects that last person left home and then set pre-configured HomeKit scene which changes all radiators to manual with lowered temperature ... then when HomeKit detects someone returned home it set all radiators to AUTO current schedule ... which as I said might be different for any period of time and is stored in the MaxCube system internally)

It is also typical behavior when one use physical radiator. You can change to manual, set end temperature and then after some time just click AUTO button and everything returns to pre-configured auto settings. I think HomeKit should emulate physical behavior as accurate as possible to have the same user experience.

BTW: there is still problem with presenting temperature from wall thermostat - it shows zero all the time 🙁

Aleksander
