### ISSUE TITLE
Openhab2/Homebridge-platform-maxcube

### ISSUE THREAD

**Issue by skatehouse** [tobsch/homebridge-platform-maxcube#33]
Hi all!
I´m using a RaspberryPi3 with installed openhabian Image and running openhab2 and homebridge exposed to Apple homekit. Every Item works. 

Problem 1: In my openhab2 exposed thermostats I can manage to raise the temperature from 4,5 to 31,5 degrees. homebridge is starting at 10 degrees. How can I set that to 4,5 so that the thermostat indicates OFF? (SOLVED) -> theromostat.js

Problem 2: I only like to have Auto, Manual and OFF in the mode-control. 
Here it is Auto/Heating/Cooling/OFF. How can I realize a mapping through homebridge like that:

Problem 3: Auto: Weekprofile in thermostats sets the temperature of the current time. e.g. It´s 3 p.m., and the stored weekprofile has as temperature of 17 degrees, the 17 degrees are set. 
Here: If you go back from OFF or heating/cooling the comfort temperature is set. 

Problem 4: OFF: should be set to 4.5 degrees (regardless of Auto/Manu) If thermostat is in Auto Mode it should stay there

Problem 5: Manu: Thermostat should hold the temperature it has actually, but changes to manu. 

 I know that it would be a change which only affects me :-) Maybe you have a hint that I can handle it myself :-\

**Comment by normen** [comment]
1) You can't really, for this plugin 10deg is "off", it doesn't expect you to have a heater outside or in a cooling room. The source is available though, you can set that to anything you like.
2) This is simply what HomeKit offers for thermostats, no way we can change that
3) Yeah, HomeKit doesn't know anything about the plan in Max! and the cube doesn't publish it either
4) Why "should"? If you think it "should" be that way then again, the source is available.
5) Wat? I don't think that sentence makes sense.

As for helping you with the changes - no not really, I can't give support for this free software, much less give free programming lessons.

**Comment by skatehouse** [comment]
1. If a thermostat shows the word OFF at 4,5 degrees then 10 degrees are definately not off. But I managed to change that. 
2. Ok
3. In openhab it does. Setting the thermostat from manual to auto overrides the manual temperature and the temperature of the weekday profile is set immediately.
4. I can´t - you can
5. Let´s say you are in Auto Mode ( 22°C) and you want to change the temperature to a certain value (17°C) it doesn´t make sense if any other temperature is set through homekit. Why not keeping the temperature of the mode that was set before?

I´m not a programmer, just an ordinary user who looked for some help and although there are only a bunch of people who care about this plugin I was very happy to find a plugin in homebridge. Thanks for that. 
I thought that just talking about my problems with the plugin could convince me to leave that plugin installed - because it´s very stable. 

Only one point I can´t forget:
I was very upset about your answer, because I thought you would answer in a more friendly way. 
Things are said now - keep on programming! My strength is more to be kind.

**Comment by normen** [comment]
Just try to imagine me saying that in a friendly voice. See the people in the world aren't against you, they are for themselves.
